# -*- coding: utf-8 -*-
"""Legacy prototype export from Colab.

This file is not used by the live Gradio application in app.py.

Virtual_Assistant_Project .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1plBEKf4MWYC9IJMgj3sq5E77QTd3pnnz
"""

# ==============================
# STEP 1 - Mount Google Drive
# ==============================

from google.colab import drive
drive.mount('/content/drive')

# ==============================
# STEP 2 - Imports
# ==============================

import os
from pathlib import Path
import pandas as pd
import librosa
import librosa.display
import matplotlib.pyplot as plt
import numpy as np
from IPython.display import Audio, display
from sklearn.metrics.pairwise import cosine_similarity

# ==============================
# STEP 3 - Define your dataset path
# ==============================

# IMPORTANT:
# Replace this path if your folder is located elsewhere in your Drive.
BASE_PATH = Path("/content/drive/MyDrive/MDTI/AI- Virtual assistant/Project /user_verification")

print("Base path exists:", BASE_PATH.exists())
print("Base path:", BASE_PATH)

# ==============================
# STEP 4 - Scan all audio files
# ==============================

data = []

# We go through both splits: enrollment and test
for split in ["enrollment", "test"]:
    split_path = BASE_PATH / split

    # Skip if folder does not exist
    if not split_path.exists():
        print(f"Warning: {split_path} does not exist")
        continue

    # Each subfolder is treated as the speaker label
    for speaker_folder in split_path.iterdir():
        if not speaker_folder.is_dir():
            continue

        speaker = speaker_folder.name

        # Read all .m4a files in that speaker folder
        for audio_file in speaker_folder.glob("*.m4a"):
            data.append({
                "split": split,
                "speaker": speaker,
                "filename": audio_file.name,
                "filepath": str(audio_file)
            })

# Create a dataframe
df_files = pd.DataFrame(data)

print("Number of files found:", len(df_files))
df_files.head(10)

# ==============================
# STEP 5 - Check class distribution
# ==============================

print("\nFiles per split and speaker:")
display(df_files.groupby(["split", "speaker"]).size().reset_index(name="count"))

# ==============================
# STEP 6 - Quick sanity checks
# ==============================

print("Unique speakers found:", df_files["speaker"].unique())
print("Unique splits found:", df_files["split"].unique())

"""## Preprocessing and MFCC Extraction for User Verification

In this step, we prepare the audio files so they all have the same format before extracting speaker-related features.

More specifically, we:
- resample all audio files to **16 kHz**
- make every audio clip exactly **2.5 seconds**
- truncate longer files
- pad shorter files with zeros
- extract **MFCCs**, which are commonly used compact audio features for speech and speaker tasks

The goal is to convert each recording into a standardized representation that can later be used to build voice profiles for each enrolled user and compare new test recordings against them.
"""

# ==============================
# STEP 12 - Global parameters
# ==============================

# We standardize all audio clips to the same sampling rate
TARGET_SR = 16000

# We choose a fixed duration of 2.5 seconds for each clip
TARGET_DURATION = 2.5  # seconds

# Total number of samples expected for each audio clip
TARGET_LENGTH = int(TARGET_SR * TARGET_DURATION)

# Number of MFCC coefficients to extract
N_MFCC = 13

print("Target sampling rate:", TARGET_SR)
print("Target duration (s):", TARGET_DURATION)
print("Target number of samples:", TARGET_LENGTH)
print("Number of MFCCs:", N_MFCC)

# ==============================
# STEP 13 - Audio preprocessing function
# ==============================

def load_and_preprocess_audio(file_path, target_sr=16000, target_length=40000):
    """
    Load an audio file, resample it, and force it to a fixed length.

    Steps:
    1. Load the audio file with librosa
    2. Resample to the target sampling rate
    3. If the signal is longer than target_length, truncate it
    4. If the signal is shorter than target_length, pad it with zeros

    Returns:
        signal (np.array): preprocessed fixed-length audio
        sr (int): sampling rate used
    """

    # Load audio and automatically resample to target_sr
    signal, sr = librosa.load(file_path, sr=target_sr)

    # If the signal is too long, cut it
    if len(signal) > target_length:
        signal = signal[:target_length]

    # If the signal is too short, pad with zeros at the end
    elif len(signal) < target_length:
        pad_amount = target_length - len(signal)
        signal = np.pad(signal, (0, pad_amount), mode='constant')

    return signal, sr

# ==============================
# NEW STEP - Add noise augmentation
# ==============================

def add_white_noise(signal, noise_factor=0.002):
    """
    Add light white noise to an audio signal.

    Args:
        signal (np.array): original audio signal
        noise_factor (float): amplitude of the added noise

    Returns:
        noisy_signal (np.array): augmented audio signal
    """
    noise = np.random.randn(len(signal))
    noisy_signal = signal + noise_factor * noise

    # Keep values in a safe audio range
    noisy_signal = np.clip(noisy_signal, -1.0, 1.0)

    return noisy_signal

# ==============================
# STEP 14 - MFCC extraction function
# ==============================

def extract_mfcc(signal, sr, n_mfcc=13):
    """
    Extract MFCC features from a preprocessed audio signal.

    Returns:
        mfcc (np.array): shape = (n_mfcc, time_frames)
    """

    mfcc = librosa.feature.mfcc(
        y=signal,
        sr=sr,
        n_mfcc=n_mfcc
    )

    return mfcc

# ==============================
# STEP 15 - Test preprocessing on one example
# ==============================

sample_row = df_files.iloc[0]

sample_path = sample_row["filepath"]
sample_filename = sample_row["filename"]
sample_speaker = sample_row["speaker"]
sample_split = sample_row["split"]

print("Speaker:", sample_speaker)
print("Split:", sample_split)
print("Filename:", sample_filename)

# Load and preprocess the audio
signal_fixed, sr_fixed = load_and_preprocess_audio(
    sample_path,
    target_sr=TARGET_SR,
    target_length=TARGET_LENGTH
)

print("Processed sampling rate:", sr_fixed)
print("Processed signal length:", len(signal_fixed))
print("Processed duration (s):", len(signal_fixed) / sr_fixed)

# ==============================
# STEP 16 - Listen to the preprocessed audio
# ==============================

display(Audio(signal_fixed, rate=sr_fixed))

# ==============================
# STEP 17 - Plot the preprocessed waveform
# ==============================

plt.figure(figsize=(12, 4))
librosa.display.waveshow(signal_fixed, sr=sr_fixed)
plt.title(f"Preprocessed Waveform - {sample_filename}")
plt.xlabel("Time (seconds)")
plt.ylabel("Amplitude")
plt.show()

# ==============================
# STEP 18 - Extract and plot MFCCs
# ==============================

mfcc_example = extract_mfcc(signal_fixed, sr_fixed, n_mfcc=N_MFCC)

print("MFCC shape:", mfcc_example.shape)

plt.figure(figsize=(12, 5))
librosa.display.specshow(mfcc_example, sr=sr_fixed, x_axis='time')
plt.colorbar()
plt.title(f"MFCCs - {sample_filename}")
plt.xlabel("Time")
plt.ylabel("MFCC Coefficients")
plt.show()

"""## From MFCC Matrices to Fixed-Size Speaker Vectors

In our Activity 1 work, we already used **MFCCs** as the main audio representation. However, MFCC extraction produces a matrix of shape `(n_mfcc, time_frames)`, which means that each recording is represented by multiple feature values over time rather than by one fixed-size vector.

For the user verification module, we need a compact **voice profile** representation for each recording so that we can compare a new test recording against the enrolled users. A simple and effective way to do this is to summarize each MFCC coefficient over time using:
- its **mean**: **mean** of each MFCC coefficient over time
- its **standard deviation**: **standard deviation** of each MFCC coefficient over time

This produces one fixed-size feature vector per recording.  
With 13 MFCC coefficients, the final vector contains:
- 13 mean values
- 13 standard deviation values  
for a total of **26 features**

These vectors will later be used to:
- build one enrollment profile per speaker
- compare test recordings against those profiles


This makes it a suitable first approach for our project, especially since our proposal is based on creating a small voice profile for each of the three enrolled users and comparing new recordings against those saved profiles.
MFCCs are extracted as a matrix with shape `(n_mfcc, time_frames)`, where the number of time frames can vary across recordings.

"""

# ==============================
# STEP 19 - Convert MFCCs to a fixed-size vector
# ==============================

def mfcc_to_fixed_vector(mfcc):
    """
    Convert an MFCC matrix of shape (n_mfcc, time_frames)
    into a fixed-size feature vector.

    We summarize each MFCC coefficient across time using:
    - mean
    - standard deviation

    Returns:
        feature_vector (np.array): shape = (2 * n_mfcc,)
    """

    # Mean of each MFCC coefficient over time
    mfcc_means = np.mean(mfcc, axis=1)

    # Standard deviation of each MFCC coefficient over time
    mfcc_stds = np.std(mfcc, axis=1)

    # Concatenate means and stds into one fixed vector
    feature_vector = np.concatenate([mfcc_means, mfcc_stds])

    return feature_vector

# ==============================
# STEP 20 - Test fixed-size vector creation
# ==============================

feature_vector_example = mfcc_to_fixed_vector(mfcc_example)

print("Feature vector shape:", feature_vector_example.shape)
print("Feature vector:")
print(feature_vector_example)

# ==============================
# STEP 21 - Full pipeline: file path to speaker vector
# ==============================

def extract_speaker_vector(file_path, target_sr=16000, target_length=40000, n_mfcc=13):
    """
    Full pipeline:
    1. Load and preprocess the audio
    2. Extract MFCCs
    3. Convert MFCCs to a fixed-size vector

    Returns:
        feature_vector (np.array): shape = (2 * n_mfcc,)
    """

    signal, sr = load_and_preprocess_audio(
        file_path,
        target_sr=target_sr,
        target_length=target_length
    )

    mfcc = extract_mfcc(signal, sr, n_mfcc=n_mfcc)
    feature_vector = mfcc_to_fixed_vector(mfcc)

    return feature_vector

# ==============================
# NEW STEP - Speaker vector extraction with optional augmentation
# ==============================

def extract_augmented_speaker_vectors(
    file_path,
    target_sr=16000,
    target_length=40000,
    n_mfcc=13,
    noise_factors=None
):
    """
    Extract the original speaker vector plus optional noisy augmented versions.

    Args:
        file_path (str): path to the audio file
        noise_factors (list or None): list of noise levels to apply

    Returns:
        vectors (list of np.array): list of speaker vectors
    """
    if noise_factors is None:
        noise_factors = []

    # Load and preprocess original signal
    signal, sr = load_and_preprocess_audio(
        file_path=file_path,
        target_sr=target_sr,
        target_length=target_length
    )

    vectors = []

    # Original vector
    mfcc = extract_mfcc(signal, sr, n_mfcc=n_mfcc)
    original_vector = mfcc_to_fixed_vector(mfcc)
    vectors.append(original_vector)

    # Augmented vectors
    for noise_factor in noise_factors:
        noisy_signal = add_white_noise(signal, noise_factor=noise_factor)
        noisy_mfcc = extract_mfcc(noisy_signal, sr, n_mfcc=n_mfcc)
        noisy_vector = mfcc_to_fixed_vector(noisy_mfcc)
        vectors.append(noisy_vector)

    return vectors

# ==============================
# STEP 22 - Extract speaker vectors for all files
# With augmentation for enrollment only
# ==============================

# Noise levels used for enrollment augmentation
ENROLLMENT_NOISE_FACTORS = [0.002, 0.005]

all_features = []

for _, row in df_files.iterrows():
    file_path = row["filepath"]
    split = row["split"]
    speaker = row["speaker"]
    filename = row["filename"]

    # --------------------------------------------------
    # Enrollment: keep original + add noisy versions
    # Test: keep only the original
    # --------------------------------------------------
    if split == "enrollment":
        feature_vectors = extract_augmented_speaker_vectors(
            file_path=file_path,
            target_sr=TARGET_SR,
            target_length=TARGET_LENGTH,
            n_mfcc=N_MFCC,
            noise_factors=ENROLLMENT_NOISE_FACTORS
        )
    else:
        feature_vectors = extract_augmented_speaker_vectors(
            file_path=file_path,
            target_sr=TARGET_SR,
            target_length=TARGET_LENGTH,
            n_mfcc=N_MFCC,
            noise_factors=[]
        )

    # Save all vectors
    for aug_idx, feature_vector in enumerate(feature_vectors):
        feature_dict = {
            "split": split,
            "speaker": speaker,
            "filename": filename,
            "filepath": file_path,
            "augmentation_id": aug_idx,
            "is_augmented": aug_idx > 0
        }

        for i, value in enumerate(feature_vector):
            feature_dict[f"f_{i}"] = value

        all_features.append(feature_dict)

# Convert to dataframe
df_features = pd.DataFrame(all_features)

print("Feature dataframe shape:", df_features.shape)
df_features.head()

# ==============================
# CHECK - Distribution after augmentation
# ==============================

display(
    df_features.groupby(["split", "speaker", "is_augmented"])
    .size()
    .reset_index(name="count")
)

# ==============================
# STEP 23 - Quick check of extracted features
# ==============================

feature_columns = [col for col in df_features.columns if col.startswith("f_")]

print("Number of feature columns:", len(feature_columns))
print("Feature columns:", feature_columns[:5], "...", feature_columns[-5:])

# ==============================
# STEP 24 - Check for missing values
# ==============================

print("Any missing values in the feature dataframe?")
print(df_features.isnull().sum().sum())

# ==============================
# STEP 25 - Check distribution in feature dataframe
# ==============================

display(df_features.groupby(["split", "speaker"]).size().reset_index(name="count"))

"""## Building Enrollment Profiles and Comparing Test Recordings

Now that each audio file has been converted into a fixed-size speaker vector, we can build one **enrollment profile** per user.

For each enrolled speaker, we compute the average of all their enrollment vectors.  
This average vector becomes the speaker’s **voice profile**.

Then, for each test recording, we compare its vector to each enrolled profile using **cosine similarity**:
- a higher cosine similarity means the test recording is closer to that enrolled speaker
- the enrolled speaker with the highest score is selected as the best match

At this stage, we first evaluate the system **without rejection**, meaning every test file is assigned to the closest enrolled speaker.  
After that, we will add a threshold so that low-confidence matches can be labeled as **unknown**.
"""

# ==============================
# STEP 27 - Split enrollment and test data
# ==============================

# Keep only enrolled speakers for profile creation
df_enrollment = df_features[df_features["split"] == "enrollment"].copy()

# Keep test files for evaluation
df_test = df_features[df_features["split"] == "test"].copy()

print("Enrollment shape:", df_enrollment.shape)
print("Test shape:", df_test.shape)

# ==============================
# STEP 28 - Define feature columns
# ==============================

feature_columns = [col for col in df_features.columns if col.startswith("f_")]

print("Number of feature columns:", len(feature_columns))

# ==============================
# STEP 29 - Build one average enrollment profile per speaker
# ==============================

# We exclude "unknown" because unknown is not an enrolled user
enrolled_speakers = [s for s in df_enrollment["speaker"].unique() if s != "unknown"]

speaker_profiles = {}

for speaker in enrolled_speakers:
    # Select all enrollment rows for this speaker
    speaker_rows = df_enrollment[df_enrollment["speaker"] == speaker]

    # Compute the average feature vector across all enrollment files
    mean_profile = speaker_rows[feature_columns].mean(axis=0).values

    # Store the profile in a dictionary
    speaker_profiles[speaker] = mean_profile

print("Enrolled speakers:", enrolled_speakers)
print("Number of profiles created:", len(speaker_profiles))

# ==============================
# STEP 30 - Check one profile
# ==============================

for speaker, profile in speaker_profiles.items():
    print(f"{speaker}: profile shape = {profile.shape}")

# ==============================
# STEP 31 - Compare one test vector to all speaker profiles
# ==============================

def compare_to_profiles(test_vector, speaker_profiles):
    """
    Compare one test vector to all enrolled speaker profiles
    using cosine similarity.

    Returns:
        scores (dict): {speaker_name: cosine_similarity_score}
    """

    scores = {}

    # Reshape test vector for sklearn
    test_vector_2d = test_vector.reshape(1, -1)

    for speaker, profile_vector in speaker_profiles.items():
        profile_vector_2d = profile_vector.reshape(1, -1)

        score = cosine_similarity(test_vector_2d, profile_vector_2d)[0][0]
        scores[speaker] = score

    return scores

# ==============================
# STEP 32 - Test comparison on one test file
# ==============================

sample_test_row = df_test.iloc[0]

sample_test_vector = sample_test_row[feature_columns].values.astype(float)
sample_test_true_speaker = sample_test_row["speaker"]
sample_test_filename = sample_test_row["filename"]

scores = compare_to_profiles(sample_test_vector, speaker_profiles)

print("Filename:", sample_test_filename)
print("True speaker:", sample_test_true_speaker)
print("Similarity scores:")
print(scores)

# ==============================
# STEP 33 - Pick the best matching speaker
# ==============================

best_speaker = max(scores, key=scores.get)
best_score = scores[best_speaker]

print("\nPredicted speaker:", best_speaker)
print("Best score:", best_score)

# ==============================
# STEP 34 - Predict the closest enrolled speaker for all test files
# ==============================

results = []

for _, row in df_test.iterrows():
    test_vector = row[feature_columns].values.astype(float)
    true_speaker = row["speaker"]
    filename = row["filename"]

    scores = compare_to_profiles(test_vector, speaker_profiles)

    best_speaker = max(scores, key=scores.get)
    best_score = scores[best_speaker]

    result_row = {
        "filename": filename,
        "true_speaker": true_speaker,
        "predicted_speaker_no_threshold": best_speaker,
        "best_score": best_score
    }

    # Add all per-speaker scores to the result table
    for speaker_name, score_value in scores.items():
        result_row[f"score_{speaker_name}"] = score_value

    results.append(result_row)

df_results = pd.DataFrame(results)

print("Results dataframe shape:", df_results.shape)
df_results.head()

# ==============================
# STEP 35 - Inspect prediction results
# ==============================

display(df_results[[
    "filename",
    "true_speaker",
    "predicted_speaker_no_threshold",
    "best_score"
]].head(15))

# ==============================
# STEP 36 - Accuracy on known speakers only
# ==============================

known_speakers = ["Adjmal", "Nair", "Sharma"]

df_known = df_results[df_results["true_speaker"].isin(known_speakers)].copy()

known_accuracy = (
    df_known["true_speaker"] == df_known["predicted_speaker_no_threshold"]
).mean()

print("Known-speaker accuracy without threshold:", round(known_accuracy, 4))

# ==============================
# STEP 37 - Inspect unknown files without rejection
# ==============================

df_unknown = df_results[df_results["true_speaker"] == "unknown"].copy()

display(df_unknown[[
    "filename",
    "true_speaker",
    "predicted_speaker_no_threshold",
    "best_score"
]].head(15))

"""## Adding a Rejection Threshold

So far, each test recording is always assigned to the enrolled speaker with the highest cosine similarity score.

This works reasonably well for known users, but it does not allow the system to reject voices from speakers who are not enrolled. As a result, all `unknown` recordings are currently forced to match one of the three enrolled users.

To make the system behave more like a real user verification module, we now introduce a **rejection threshold**:
- if the best cosine similarity score is **high enough**, we accept the predicted enrolled speaker
- if the best score is **below the threshold**, we label the recording as `unknown`

We will first inspect the score distributions for known and unknown test recordings, then choose a threshold empirically.
"""

# ==============================
# STEP 38 - Compare best-score distributions
# ==============================

import matplotlib.pyplot as plt

# Best scores for known enrolled speakers
known_scores = df_results[df_results["true_speaker"].isin(["Adjmal", "Nair", "Sharma"])]["best_score"]

# Best scores for unknown speakers
unknown_scores = df_results[df_results["true_speaker"] == "unknown"]["best_score"]

plt.figure(figsize=(10, 5))
plt.hist(known_scores, bins=10, alpha=0.6, label="Known speakers")
plt.hist(unknown_scores, bins=10, alpha=0.6, label="Unknown speakers")
plt.xlabel("Best cosine similarity score")
plt.ylabel("Number of files")
plt.title("Best-score distribution: known vs unknown")
plt.legend()
plt.show()

# ==============================
# STEP 39 - Score summary statistics
# ==============================

print("Known score summary:")
display(known_scores.describe())

print("Unknown score summary:")
display(unknown_scores.describe())

# ==============================
# STEP 40 - Evaluate multiple thresholds
# ==============================

thresholds = [0.98, 0.985, 0.99, 0.992, 0.995, 0.997]

evaluation_rows = []

for threshold in thresholds:
    predicted_with_threshold = []

    for _, row in df_results.iterrows():
        if row["best_score"] >= threshold:
            predicted_with_threshold.append(row["predicted_speaker_no_threshold"])
        else:
            predicted_with_threshold.append("unknown")

    temp_df = df_results.copy()
    temp_df["predicted_with_threshold"] = predicted_with_threshold

    # Accuracy on known speakers only
    temp_known = temp_df[temp_df["true_speaker"].isin(["Adjmal", "Nair", "Sharma"])]
    known_accuracy = (temp_known["true_speaker"] == temp_known["predicted_with_threshold"]).mean()

    # Rejection accuracy on unknown speakers
    temp_unknown = temp_df[temp_df["true_speaker"] == "unknown"]
    unknown_rejection_rate = (temp_unknown["predicted_with_threshold"] == "unknown").mean()

    # Overall accuracy
    overall_accuracy = (temp_df["true_speaker"] == temp_df["predicted_with_threshold"]).mean()

    evaluation_rows.append({
        "threshold": threshold,
        "known_accuracy": known_accuracy,
        "unknown_rejection_rate": unknown_rejection_rate,
        "overall_accuracy": overall_accuracy
    })

df_threshold_eval = pd.DataFrame(evaluation_rows)
display(df_threshold_eval)

"""## Threshold Selection

We selected a cosine-similarity threshold of **0.995** for the user verification module.

This choice reflects a **security-oriented design**: Atlas should only unlock when the similarity with an enrolled user profile is sufficiently high. A stricter threshold reduces the risk of accepting unknown speakers, even though it may also reject some valid enrolled users.

In our experiments, this threshold provided a stronger rejection behavior for unknown speakers, which is consistent with the intended role of the verification module: keeping Atlas locked unless there is a strong enough voice match with one of the enrolled team members.

With a threshold of 0.995, the system becomes more conservative.  
It is less likely to unlock for an unknown speaker, which improves security, but it also increases the chance of rejecting a valid enrolled user. This reflects the classical trade-off in user verification between **security** and **user convenience**.

"""

# ==============================
# STEP 41 - Choose a threshold
# ==============================

# Change this value after inspecting the table
CHOSEN_THRESHOLD = 0.995
# ==============================
# STEP 42 - Final predictions with threshold
# ==============================

df_results["predicted_speaker_with_threshold"] = df_results.apply(
    lambda row: row["predicted_speaker_no_threshold"]
    if row["best_score"] >= CHOSEN_THRESHOLD
    else "unknown",
    axis=1
)

display(df_results[[
    "filename",
    "true_speaker",
    "predicted_speaker_no_threshold",
    "best_score",
    "predicted_speaker_with_threshold"
]].head(20))

# ==============================
# STEP 43 - Final evaluation with chosen threshold
# ==============================

final_overall_accuracy = (
    df_results["true_speaker"] == df_results["predicted_speaker_with_threshold"]
).mean()

final_known_accuracy = (
    df_results[df_results["true_speaker"].isin(["Adjmal", "Nair", "Sharma"])]["true_speaker"]
    ==
    df_results[df_results["true_speaker"].isin(["Adjmal", "Nair", "Sharma"])]["predicted_speaker_with_threshold"]
).mean()

final_unknown_rejection_rate = (
    df_results[df_results["true_speaker"] == "unknown"]["predicted_speaker_with_threshold"] == "unknown"
).mean()

print("Final overall accuracy:", round(final_overall_accuracy, 4))
print("Final known-speaker accuracy:", round(final_known_accuracy, 4))
print("Final unknown rejection rate:", round(final_unknown_rejection_rate, 4))

# ==============================
# STEP 44 - Inspect unknown predictions after threshold
# ==============================

display(
    df_results[df_results["true_speaker"] == "unknown"][[
        "filename",
        "true_speaker",
        "best_score",
        "predicted_speaker_with_threshold"
    ]]
)

# ==============================
# STEP 45 - Final confusion matrix
# ==============================

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

labels = ["Adjmal", "Nair", "Sharma", "unknown"]

cm = confusion_matrix(
    df_results["true_speaker"],
    df_results["predicted_speaker_with_threshold"],
    labels=labels
)

disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=labels)

plt.figure(figsize=(7, 7))
disp.plot(cmap="Blues", values_format="d")
plt.title("Final Confusion Matrix - User Verification")
plt.show()

# ==============================
# STEP 46 - Inspect errors
# ==============================

df_errors = df_results[
    df_results["true_speaker"] != df_results["predicted_speaker_with_threshold"]
].copy()

display(df_errors[[
    "filename",
    "true_speaker",
    "best_score",
    "predicted_speaker_with_threshold"
]])

"""## Interpretation of User Verification Results

The final user verification system was built using:
- MFCC-based audio features
- mean and standard deviation pooling
- average enrollment profiles for each enrolled speaker
- cosine similarity for profile comparison
- a rejection threshold of **0.995**

This threshold was chosen to favor **security** over convenience. In other words, Atlas should remain locked unless the test recording is sufficiently close to one of the enrolled user profiles.

The results show that this stricter threshold improves rejection of unknown speakers, but also causes some valid enrolled users to be rejected. This illustrates the expected trade-off in speaker verification:
- **lower threshold** → easier access, but weaker protection
- **higher threshold** → stronger protection, but more false rejections

For our project, this stricter setting is acceptable because the main goal of the verification module is to avoid unlocking Atlas for non-enrolled users.
"""
